env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-2
  setup_script:
    - pkg install -y autoconf automake libtool pkgconf fusefs-libs
    - pkg install -y lzo2 liblz4 zstd
    - pkg install -y squashfs-tools coreutils
    - kldload fuse
    - sysctl vfs.usermount=1
  build_script:
    - ./autogen.sh
    - CPPFLAGS="-I/usr/local/include -Werror" LDFLAGS="-L/usr/local/lib" ./configure
    - make
  test_script:
    - make check
    - diff -u ci/expected-features/all ci/features
  install_script:
    - sudo make install
  always:
    after_script:
    - cat config.log || true
    - cat tests/*.log || true
    - mksquashfs || true

netbsd_task:
  container:
    kvm: true
    image: vasi/netbsd
  qemu_background_script:
    - SSH_PORT=4446 /scripts/qemu-start.sh | tee /var/log/qemu.log
  build_script:
    # Wait for SSH, then run a script
    - for i in {1..10}; do ssh -p 4446 -oConnectTimeout=5 -oStrictHostKeyChecking=no localhost true && break || echo "waiting for SSH" && sleep 5; done
    - du -sh $PWD
    - scp -P 4446 -oStrictHostKeyChecking=no -qr $PWD localhost:/squashfuse
    - ssh -p 4446 -oStrictHostKeyChecking=no localhost /squashfuse/ci/netbsd.sh
  always:
    after_script:
      - cat /var/log/qemu.log
