language: c
compiler: gcc
jobs:
  - name: ARM
    os: linux
    arch: arm64
    dist: bionic
    env: CHECK_FEATURES=all
  - name: Big-endian
    os: linux
    arch: s390x
    dist: bionic
    env: CHECK_FEATURES=all
env:
  global:
    - MAKEFLAGS="-j3 V=1"
addons:
  apt:
    update: true
    packages:
      - automake
      - autoconf
      - libtool
      - pkg-config
      - fuse
      - fio
      - libfuse-dev
      - zlib1g-dev
      - liblzo2-dev
      - liblzma-dev
      - liblz4-dev
      - libzstd-dev
script:
  - ./autogen.sh
  - CPPFLAGS="-Werror" ./configure $DISABLE_FUSE
  - make
  - make check
  - diff -u ci/expected-features/$CHECK_FEATURES ci/features
  - sudo make install
after_script:
  - cat config.log || true
  - cat tests/*.log || true
  - mksquashfs || true
