name: Github Actions CI
on:
  push:
  pull_request:
  schedule:
    # Every friday
    - cron: '0 0 * * 5'
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install autoconf automake libtool pkgconfig squashfs coreutils
          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask osxfuse
      - name: build
        run: |
          ./autogen.sh
          CPPFLAGS="-Werror" ./configure
          make -j3 V=1
      - name: test
        run: |
          make check
          diff -u ci/expected-features/all ci/features
      - name: install
        run: sudo make install
      - name: output
        run: mksquashfs > mksquashfs.log || true
        if: always()
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            config.log
            tests/*.log
            mksquashfs.log
            ci/features
        if: always()
  windows:
    runs-on: windows-2019
    steps:
      - name: install chocolatey dependencies
        shell: powershell
        run: choco install -y squashfs 
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: checkout
        uses: actions/checkout@v2
      - name: generate header
        shell: bash
        run: ./gen_swap.sh squashfs_fs.h
      - name: build
        working-directory: ./win
        shell: powershell
        run: MSBuild.exe squashfuse_ls.vcxproj -p:PlatformToolset=v142
      - name: test
        working-directory: ./win
        shell: bash
        run: |
          set -x
          mkdir test
          touch test/foo test/bar test/'iggy blah'
          mksquashfs test test.squashfs
          ls test | sort > expected
          ./Debug/squashfuse_ls.exe test.squashfs | dos2unix | sort > actual
          diff -u expected actual
